### ISSUE TITLE
makefile:13: recipe for target 'xorg.o' failed

### ISSUE THREAD

**Issue by major** [MeanEYE/Disk-Indicator#7]
Currently trying to compile it on Fedora 21 running gcc 4.9.2 and getting this:

```
c99 -Wall -pedantic -Werror -D _BSD_SOURCE -c src/xorg.c
In file included from /usr/include/stdio.h:27:0,
                 from src/xorg.c:30:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
cc1: all warnings being treated as errors
makefile:13: recipe for target 'xorg.o' failed
make: *** [xorg.o] Error 1
```

If I remove `-Werror` from the makefile, it compiles just fine.

**Comment by MeanEYE** [comment]
That `_BSD_SOURCE` is such a nightmare. Thanks for reporting it. This is third time I change it to something else. Can you see if it works when you change `_BSD_SOURCE` to `_DEFAULT_SOURCE`?

**Comment by major** [comment]
That fixed it.

![BAM](http://rushmessageboard.com/public/style_emoticons/default/EMERIL%20BAM%20crop.jpg)

**Comment by MeanEYE** [comment]
Okay, I won't close it just now, because I want to make sure it compiles on other systems as well. Thanks for reporting it.

**Comment by MeanEYE** [comment]
Change committed.
